config/routes.rb
Rails.application.routes.draw do

  resources :bases

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :attendances do
    collection do
      get 'csv_output'
    end
  end
    
  resources :users do
    collection { post :import }
    get 'import', to: 'users#import'
    get 'index_attendance', to: 'users#index_attendance'
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/edit_attendance_log'
      get 'attendances/edit_notice_overtime'
      get 'attendances/edit_change_attendance'
      post 'approvals/create'
      get 'approvals/edit'
    end
    resources :attendances do
      patch 'update'
      # datetimeのnew
      get 'new'
      member do      
        # 残業申請モーダル
        get 'edit_overtime_app'
        patch 'update_over_app'
        # 残業申請のお知らせモーダルの更新
        patch 'update_notice_overtime'
        # 勤怠変更申請のお知らせモーダルの更新
        patch 'update_change_attendance'
      end
    end
    resources :approvals do
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/approval.rb
class Approval < ApplicationRecord
  belongs_to :user
  
  enum confirm: { "申請中" => 1, "承認" => 2, "否認" => 3 }
end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  before_action :set_user, only: [:create, :edit]
  before_action :logged_in_user, only: [:create, :edit, :update, :approval_invalid?]

  
  def create
    if params[:approval][:name].present?
      @approval_create = @user.approvals.build(superior_id: params[:approval][:name], month_at: params[:format], confirm: "申請中")
      if @approval_create.save
        flash[:success] = "1ヶ月分の勤怠申請をしました。"
        redirect_to user_path(@user)
      else
        flash[:danger] = "1ヶ月分の勤怠申請に失敗しました。"
        redirect_to user_path(@user)
      end
    else
      flash[:danger] = "所属長を選択してください。"
      redirect_to user_path(@user)
    end
  end
  
  def edit
    @users = User.where(id: Approval.where(superior_id: @user.id).where(confirm: "申請中").where.not(month_at: nil).select(:user_id)).where.not(id: current_user)
    @users.each do |user| 
      @approvals = Approval.where(superior_id: @user.id).where.not(month_at: nil)
      @approvals.each do |approval|
        @ap = approval
      end
    end
  end
  
  def approval_invalid?
    items = []
    approval_params.each do |id, item|
      items << item[:approval_flag]
    end
    if items.all?{|i| i == "false"}
      return false
    else
      return true
    end
  end
  
  def update
    @user = User.find(params[:user_id])
    if approval_invalid?
      approval_params.each do |id, item|
      approval = Approval.find(id)
        if params[:approval][:updated_approvals][id][:approval_flag] == "true"
          approval.update_attributes(confirm: item[:confirm], approval_flag: false)
        end
      end
      flash[:success] = "1ヶ月分勤怠申請を変更しました"
      redirect_to @user
    else
      flash[:danger] = "変更にチェックがありません。"
      redirect_to @user
    end
  end
  
  
  
  private
    def approval_format_params
      params.permit(:format)
    end
    def approval_name_params
      params.require(:approval).permit(:name)
    end
  
    def approval_params
      params.require(:approval).permit(updated_approvals:[:confirm, :approval_flag])[:updated_approvals]
    end
end

app/helpers/approvals_helper.rb
module ApprovalsHelper
  # 1ヶ月分の勤怠申請のお知らせモーダル更新バリデーション
#   def approval_invalid?
#     items = []
#     approval_params.each do |id, item|
#       items << item[:approval_flag]
#     end
#     if items.all?{|i| i == "false"}
#       return false
#     else
#       return true
#     end
#   end
end

app/views/approvals/_edit.html.erb
<% provide(:button_text, '変更を送信する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <%= form_with(model: @approvals, url: user_approval_path(@user, @ap), local: true, method: :patch) do |f| %>
      <% @users.each do |user| %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h3 class="modal-title text-center">【<%= user.name %>】からの1ヶ月分勤怠申請</h3>
          </div>
          <table class="table table-bordered table-condensed table-hover table-striped" id="table-attendances">
            <thead>
              <tr>
                <th>月</th>
                <th>指示者確認㊞</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
              </tr>
            </thead>
            <% @approval_list = Approval.where(superior_id: @user.id).where(user_id: user.id).where(confirm: "申請中").where(approval_flag: false) %>
            <% @approval_list.each do |approval| %>
              <%= f.fields_for "updated_approvals[]", approval do |a|  %>
              <tbody>
                <tr>
                  <td><%= l(approval.month_at, format: :month) %></td>
                  <td><%= a.select :confirm, Approval.confirms.keys.to_a, include_blank: true, selected: nil %></td>
                  <td><%= a.check_box :approval_flag, {class: "approval_flag"}, 'true', 'false' %></td>
                  <td><%= link_to "確認", user_path(user.id), class: "btn btn-primary btn-md" %></td>
                </tr>
              </tbody>
              <% end %>
            <% end %>
          </table>
        <% end %>
        <div class="notice_update_submit"><%= f.submit yield(:button_text), class: "btn btn-primary btn-lg center-block" %></div>
      <% end %>
  </div>
</div>

app/views/approvals/create.html.erb
<h1>Approvals#create</h1>
<p>Find me in app/views/approvals/create.html.erb</p>

app/views/approvals/edit.js.erb
$("#edit").html("<%= escape_javascript(render 'edit') %>");
$("#edit").modal("show");