config/routes.rb
Rails.application.routes.draw do

  resources :bases

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :attendances do
    collection do
      get 'csv_output'
    end
  end
    
  resources :users do
    collection { post :import }
    get 'import', to: 'users#import'
    get 'index_attendance', to: 'users#index_attendance'
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/edit_attendance_log'
      get 'attendances/edit_notice_overtime'
      get 'attendances/edit_change_attendance'
      post 'approvals/create'
      get 'approvals/edit'
    end
    resources :attendances do
      patch 'update'
      # datetimeのnew
      get 'new'
      member do      
        # 残業申請モーダル
        get 'edit_overtime_app'
        patch 'update_over_app'
        # 残業申請のお知らせモーダルの更新
        patch 'update_notice_overtime'
        # 勤怠変更申請のお知らせモーダルの更新
        patch 'update_change_attendance'
      end
    end
    resources :approvals do
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :approvals, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :affiliation, length: { in: 2..30 }, allow_blank: true
  validates :basic_work_time, presence: true
  validates :work_time, presence: true
  
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
      BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil? 
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      user.save
    end
  end
  
  def csv_output
    if self.confirm == "承認"
      return true
    else
      return false
    end
  end
  
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid", "basic_work_time",
     "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end
  
  enum confirm: { "申請中" => 1, "承認" => 2, "否認" => 3 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :edit_basic_info]
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: :show
  before_action :admin_or_correct_user, only: :show
  before_action :superior_user, only: :show
  before_action :rejection_admin, only: [:show, :edit_one_month]

  def index
    @users = User.all.order('id ASC')
  end
 
  def import
    unless params[:file].blank?
      if File.extname(params[:file].original_filename) == ".csv"
        # 保存と結果のメッセージを取得して表示
        User.import(params[:file])
        flash[:info] = "CSVファイルをインポートしました。"
        redirect_to users_path
      else
        flash[:danger] = "読み込み可能なファイルはCSV形式のみです"
        redirect_to users_path
      end
    else
      flash[:danger] = "読み込むCSVファイルをセットしてください"
      redirect_to users_path
    end
  end
  
  def index_attendance
    @users = User.all.includes(:attendances)
  end
    
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to users_url
    else
      render :edit      
    end
  end
  
  def destroy
    if @user.admin?
      flash[:danger] = "管理者は削除できません"
      redirect_to users_url
    else
      @user.destroy
      flash[:success] = "User deleted.."
      redirect_to users_url
    end
  end

  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
    # 残業申請のお知らせボタン
    @notice_users = User.where(id: Attendance.where.not(endtime_at: nil).select(:user_id)).where.not(id: current_user)
    @notice_users.each do |user|
      @attendances_list = Attendance.where.not(endtime_at: nil).where(overtime_check: false).where(name: current_user.name)
      @endtime_notice_sum = @attendances_list.count
      @attendances_list.each do |att_notice|
        @att_notice = att_notice
      end
    end
    
    # 勤怠変更申請のお知らせ合計
    @att_update_list = Attendance.where(attendance_change_check: false).where(attendance_change_flag: true).where(name: current_user.name)
    @att_update_sum = @att_update_list.count
    @att_update_list.each do |att_up|
      @att_up = att_up
    end
    
    # 所属長承認
    @attendance = Attendance.find_by(worked_on: @first_day)
      # 所属長承認申請するリスト
    @approval_list = Approval.where(month_at: @first_day).where(user_id: current_user)
    @approval_list.each do |approval|
      @approval = approval
      @approval_superior = User.find_by(id: @approval.superior_id)
    end
      # 所属長承認申請お知らせリスト(上長)
    @approval_notice_lists = Approval.where(confirm: "申請中").where(approval_flag: false).where(superior_id: current_user)
    @approval_notice_lists.each do |app|
      @superior_approval = app
    end
      # 所属長承認申請合計
    @approval_notice_sum = @approval_notice_lists.count
    

    # CSVインポート
    @attendance_csv = Attendance.joins(:user).where(id: Attendance.where(user_id: current_user))
  end
  
  def admin_or_correct_user
    unless current_user?(@user) || current_user.admin? || current_user.superior?
      flash[:danger] = "ログインしてください。"
      redirect_to(root_url)
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :password, :password_confirmation,
                                  :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end
    
    def basic_params
      params.require(:user).permit(:basic_time, :work_time)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min)/60.0)
  end
  
  # 時間外時間の計算
  def over_time(endtime, designated_work_end_time, day)
    if day.tommorow_index == true
      format("%.2f", (((Time.parse(endtime) - Time.parse(designated_work_end_time)) / 60) / 60.0) + 24)
    else
      format("%.2f", (((Time.parse(endtime) - Time.parse(designated_work_end_time)) / 60) / 60.0))
    end
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
          <%= render "shared/error_messages", model: f.object %>
            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :affiliation, class: "form-control" %>

            <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_work_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
<%= render "shared/error_messages", model: f.object %>
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class:"form-control" %>
  
  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>
  
  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :employee_number, class: "form-control" %>

  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class:"form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class:"form-control" %>

  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>

  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>

  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>
  
  <%= f.submit "#{yield(:button_text)}", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
  
<% end %>

app/views/users/_form_user.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= f.label :name, class: "label--edit" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label--edit" %>
  <%= f.email_field :email, class:"form-control" %>
  
  <%= f.label :affiliation, class: "label--edit" %>
  <%= f.text_field :affiliation, class: "form-control" %>
  
  <%= f.label :employee_number, class: "label--edit" %>
  <%= f.number_field :employee_number, class: "form-control" %>

  <%= f.label :uid, class: "label--edit" %>
  <%= f.text_field :uid, class: "form-control" %>
  
  <%= f.label :password, class: "label--edit" %>
  <%= f.password_field :password, class:"form-control" %>

  <%= f.label :basic_work_time, class: "label--edit" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>

  <%= f.label :designated_work_start_time, class: "label--edit" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>

  <%= f.label :designated_work_end_time, class: "label--edit" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>
  
  <%= f.submit "編集する", class: "btn btn-primary btn-block btn--edit" %>
<% end %>

app/views/users/_instructer.html.erb
<% if day.name.present? && day.endtime_at.present? %>
  <% if day.confirm == "承認" || day.confirm == "否認" %>
    <p><%= day.name %>が<strong><%= yield(:endtime_instruction) %>申請<%= day.confirm %>済</strong></p>
  <% elsif day.confirm == "申請中" %>
    <p><%= day.name %>へ<%= yield(:endtime_instruction) %><strong><%= day.confirm %></strong></p>
  <% else %>
  <!-- なし -->
  <% end %>
<% end %>

<% if (day.updated_started_at.present? && day.updated_finished_at.present?) && day.name.present? %>
  <% if day.confirm == "承認" || day.confirm == "否認" %>
    <p><%= day.name %>が<strong><%= yield(:change_attendance_instruction) %><%= day.confirm %>済</strong></p>
  <% elsif day.confirm == "申請中" %>
    <p><%= day.name %>へ<%= yield(:change_attendance_instruction) %><strong><%= day.confirm %></strong></p>
  <% else %>
  <!-- なし -->
  <% end %>
<% end %>

app/views/users/_serch_form.html.erb
<% provide(:button_text, '検索') %>

<p>ユーザー名検索</p>
<%= form_with(scope: :search, url: users_path, method: :get, local: true) do |f| %>
  <div class="input-group">
    <%= f.text_field :name, class: "form-control", placeholder: 'キーワードを入力...', value: (params[:search][:name] if params[:search]) %>
    <span class="input-group-btn">
      <%= f.submit "#{yield(:button_text)}", class: "btn btn-primary" %>
    </span>
  </div>
<% end %> 

app/views/users/edit.html.erb
<% provide(:tittle, "Edit")%>
<% provide(:class_text, "user--edi") %>
<% provide(:button_text, "更新") %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'users/form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報の修正") %>
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '編集') %>

<h1>基本情報の更新</h1>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
      <%= render "shared/error_messages", model: f.object %>
      
      <%= f.label :work_time, "指定勤務時間", class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :work_time, class: "form-control" %>
      
      <%= f.label :basic_time, "基本勤務時間", class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :basic_time, class: "form-control" %>

      <div class="center">
        <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
      </div>
    <% end %>
  </div>
</div>
  

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/edit_overtime_app.js.erb
$("#edit_overtime_app").html("<%= escape_javascript(render 'edit_overtime_app') %>");
$("#edit_overtime_app").modal("show");

app/views/users/form_user.hrml.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class:"form-control" %>
  
  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>
  
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class:"form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class:"form-control" %>
  
  <%= f.submit "#{yield(:button_text)}", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
  
<% end %>

app/views/users/index.html.erb
<% provide(:title, "ユーザ一覧") %>

<h1>ユーザ一覧</h1>
<div class="csv_holder">
  <%= form_tag import_users_path, multipart: true do %>
    <div><%= file_field_tag :file, class: "file-csv" %></div>
    <div><%= submit_tag "CSVをインポート", class: "btn btn-block btn-primary" %></div>
  <% end %>
</div>
<div>
  <p>Example</p>
</div>
<% if current_user.admin? %>
  <div class="example">
    <% @users.each do |user| %>
      <%= render partial: "shared/error_messages", collection: @user %>
      <div><%= user.name %></div>
      <div>
        <span>|</span>
        <% unless user.admin %>
          <%= link_to "削除", user, method: :delete,
              data: { confirm: "削除してよろしいですか？" },
              class: "btn btn-primary" %>
        <% end %>
      </div>
      
      <div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= user.id %>">
              <button class="btn btn-primary btn-lg w-10" type="button">編集</button></a>
            </h4>
          </div>
          <div id="collapse<%= user.id %>" class="panel-collapse collapse">
            <div class="panel-body"><%= render 'users/form_user', { user: user }  %></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/index_attendance.html.erb
<% provide(:title, "出勤中社員一覧") %>
<h1>出勤中社員一覧</h1>

<div>
  <table class="table table-bordered table-condensed table-hover text-center table-striped" id="index_attendance">
    <thead>
      <tr>
        <th>社員番号</th>
        <th>名前</th>
      </tr>  
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <% user.attendances.each do |attendance| %>
          <% if (Date.current == attendance.worked_on) && attendance.started_at != nil && attendance.finished_at == nil %>
          <tr>
            <td><%= user.employee_number %></td>
            <td><%= user.name %></td>
          </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<% provide(:title, 'アカウント作成') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'users/form' %>
  </div>
</div>