config/routes.rb
Rails.application.routes.draw do

  resources :bases

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :attendances do
    collection do
      get 'csv_output'
    end
  end
    
  resources :users do
    collection { post :import }
    get 'import', to: 'users#import'
    get 'index_attendance', to: 'users#index_attendance'
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/edit_attendance_log'
      get 'attendances/edit_notice_overtime'
      get 'attendances/edit_change_attendance'
      post 'approvals/create'
      get 'approvals/edit'
    end
    resources :attendances do
      patch 'update'
      # datetimeのnew
      get 'new'
      member do      
        # 残業申請モーダル
        get 'edit_overtime_app'
        patch 'update_over_app'
        # 残業申請のお知らせモーダルの更新
        patch 'update_notice_overtime'
        # 勤怠変更申請のお知らせモーダルの更新
        patch 'update_change_attendance'
      end
    end
    resources :approvals do
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  require 'csv'
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  
  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  validate :started_at_than_finished_at_fast_if_invalid
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
  
  enum overtime_confirm: { "申請中" => 1, "承認" => 2, "否認" => 3 }, _prefix: true
  enum confirm: { "申請中" => 1, "承認" => 2, "否認" => 3 }, _prefix: true

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  include AttendancesHelper
  before_action :set_user, only: [:edit_one_month, :update_one_month, :edit_notice_overtime,
                                  :edit_change_attendance, :edit_attendance_log]
  before_action :set_attendance, only: [:edit_overtime_app, :update_over_app, :update_notice_overtime, :update_change_attendance]
  before_action :logged_in_user, only: [:update, :edit_one_month]
  before_action :set_one_month, only: [:edit_one_month]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :superior_user, only: [:edit_overtime_app, :edit_change_attendance]
  before_action :rejection_admin, only: [:show, :edit_one_month]
  
  require 'csv'
  require 'rails/all'
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  
  def update
    @attendance = Attendance.find(params[:id])
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        @attendance.update_attributes(updated_started_at: @attendance.started_at)
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil? 
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        @attendance.update_attributes(updated_finished_at: @attendance.finished_at)
        flash[:info] = "お疲れ様でした！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  def csv_output
    user = User.find_by(id: current_user)
    @first_day = params[:date].to_date
    @last_day = @first_day.end_of_month
    @attendance = user.attendances.where(worked_on: @first_day..@last_day).order(:worked_on)
    # @attendance = Attendance.joins(:user).where(id: Attendance.where(worked_on: @first_day..@last_day).where(user_id: current_user))
    send_data render_to_string, filename: "attendances.csv", type: :csv
  end
  
  def edit_one_month  
  end
  
  def update_one_month
    ActiveRecord::Base.transaction do
      if attendances_updated_invalid?
        attendances_params.each do |id, item|
          attendance = Attendance.find(id)
          if item[:name].present?
            if attendance.attendance_change_check == true
              attendance.update_attributes!(item)
              attendance.update_attributes!(attendance_change_check: false, confirm: "申請中",
                                            before_started_at: attendance.updated_started_at, before_finished_at: attendance.updated_finished_at)
            else
              attendance.update_attributes!(item)
              attendance.update!(attendance_change_flag: true, confirm: "申請中")
            end
          end
        end
        flash[:success] = "1ヶ月分の勤怠情報を更新しました。</br>※上長が未選択のものは更新されません。".html_safe 
        redirect_to user_url(@user, date: params[:date])
      else
        flash[:danger] = "不正な入力情報がありました、再入力してください。"
        redirect_to user_url(@user, date: params[:date])
      end
    end
  rescue ActiveRecord::RecordInvalid
      flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
      redirect_to attendances_edit_one_month_user_path(@user, date: params[:date])
  end

   # 残業申請のモーダル
  def edit_overtime_app
    @attendances = Attendance.where(id: params[:id], user_id: params[:user_id])
    @today = Date.today
  end
  
  # 残業申請の更新処理
  def update_over_app
    @worktime = @user.designated_work_end_time
    @attendance = Attendance.find(params[:id])
    if overtime_params_updated_invalid?
      if params[:attendance][:name].blank?
        flash[:danger] = "上長が選択されていません。"
        redirect_to @user
      else
        @attendance.update(overtime_params)
        @attendance.update(overtime_confirm: "申請中", overtime_check: false)
        flash[:success] = "残業申請しました。"
        redirect_to @user
      end
    else
      if @attendance.updated_finished_at.blank?
        flash[:danger] = "退社時間が未入力です。"
        redirect_to @user
      elsif ((params[:attendance]["endtime_at(4i)"].to_i < @worktime.hour) &&
              params[:attendance][:tommorow_index] == "false")
        flash[:danger] = "指定勤務終了時間より早い終了予定時間は無効です。"
        redirect_to @user
      else
        flash[:danger] = "申請情報に不正な入力があるため、残業申請できませんでした。"
        redirect_to @user
      end
    end
  end
  
  # 残業申請のお知らせモーダル
  def edit_notice_overtime
    @notice_users = User.where(id: Attendance.where(name: current_user.name).where(overtime_check: false).where.not(endtime_at: nil).select(:user_id)).where.not(id: current_user)
    users(@notice_users)
  end
  
  # 残業申請お知らせの更新
  def update_notice_overtime
    # 前提:form_withのurl引数（@user）はbefore_actionの
    #      set_userによって「上長」のユーザー情報を得る。
    @notice_users = User.where(id: Attendance.where(overtime_check: false).where.not(endtime_at: nil).select(:user_id))
    users(@notice_users)
    if overtime_notice_updated_invalid?
      notice_overtime_params.each do |id, item|
        attendance = Attendance.find(id)
        if params[:attendance][:notice_attendances][id][:overtime_check] == "true"
          attendance.update_attributes(item)
        end
      end
      flash[:success] = "残業申請の変更を通知しました。</br>※変更にチェックがない申請は更新されていません。".html_safe
      redirect_to @user
    else
      flash[:danger] = "残業申請の変更ができませんでした。</br>※変更チェックボックスが選択されません。"
      redirect_to @user
    end
  end
  
  # 勤怠変更申請のお知らせモーダル表示
  def edit_change_attendance
    @att_update_list = Attendance.where.not(updated_started_at: nil).or(Attendance.where.not(updated_finished_at: nil)).where(name: @user.name)
    @users = User.where(id: Attendance.where(name: current_user.name).where(attendance_change_check: false).where(attendance_change_flag: true).where.not(updated_started_at: nil).select(:user_id)).where.not(id: current_user)
    @att_update_list.each do |att_up|
      @att_up = att_up
    end
  end

   # 勤怠変更申請お知らせモーダルの更新
  def update_change_attendance
    @att_update_list = Attendance.where.not(updated_started_at: nil).or(Attendance.where.not(updated_finished_at: nil)).where(name: current_user.name)
    if change_attendance_updated_invalid?
      change_attendance_params.each do |id, item|
        attendance = Attendance.find(id)
        if params[:attendance][:updated_attendances][id][:attendance_change_check] == "true"
          attendance.update_attributes(item)
        end
      end
      flash[:success] = "勤怠変更申請のお知らせを変更しました。</br>※変更にチェックがないものは更新されません。"
      redirect_to @user
    else
      flash[:danger] = "勤怠変更申請の変更ができませんでした。</br>※変更チェックボックスが選択されていません。"
      redirect_to @user
    end
  end
  
  # 勤怠修正ログ
  def edit_attendance_log
    @updated_attendance_list = Attendance.where.not(updated_started_at: nil).or(Attendance.where.not(updated_finished_at: nil)).where(user_id: current_user)
  end

  
  
  private
    def attendances_params
      params.require(:user).permit(:attendance_change_flag, attendances: [:updated_started_at, :updated_finished_at, :tommorow_index, :note, :name])[:attendances]
    end
    
    def overtime_params
      params.require(:attendance).permit(:endtime_at, :tommorow_index, :overtime_memo, :name)
    end
    
     def notice_overtime_params
      params.require(:attendance).permit(notice_attendances: [:overtime_confirm, :overtime_check])[:notice_attendances]
     end
     
     def change_attendance_params
      params.require(:attendance).permit(updated_attendances: [:note, :confirm, :attendance_change_check])[:updated_attendances]
     end
     
     def updated_time_params
       params.require(:user).permit(attendances: [:updated_started_at, :updated_finished_at, :tommorow_index, :note, :name])[:attendances]
     end
    
    def admin_or_correct_user
      @user = User.find(params[:user_id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
      flash[:danger] = "編集権限がありません。"
      redirect_to(root_url)
      end
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
 
  def attendance_state(attendance)
    if Date.current == attendance.worked_on
      return "出社" if attendance.started_at.nil?
      return "退社" if attendance.started_at.present? && attendance.finished_at.nil?
    end
    false
  end
  
  def working_time(start, finish, day)
    if day.tommorow_index == true
      format("%.2f", (((finish - start) / 60) / 60.0) + 24)
    else
      format("%.2f", (((finish - start) / 60) / 60.0))
    end
  end
  
  # 時間外時間の計算
  def over_time(endtime, designated_work_end_time, day)
    if day.tommorow_index == true
      format("%.2f", (((Time.parse(endtime) - Time.parse(designated_work_end_time)) / 60) / 60.0) + 24)
    else
      format("%.2f", (((Time.parse(endtime) - Time.parse(designated_work_end_time)) / 60) / 60.0))
    end
  end
  
  
  def css_class(wo)
    case $days_of_the_week[wo.wday]
    when '土'
      'text-primary'
    when '日'
      'text-danger'
    end
  end
  
  # 勤怠編集のバリデーション
  def attendances_updated_invalid?
      attendances = true
      attendances_params.each do |id, item|
        if item[:updated_started_at].blank? && item[:updated_finished_at].blank?
          next
        elsif item[:updated_started_at].blank? || item[:updated_finished_at].blank?
          attendances = false
          break
        elsif item[:tommorow_index] == "false" && item[:updated_started_at] > item[:updated_finished_at]
          attendances = false
          break
        end
      end
      return attendances
  end
  
  # ###
  
  # 残業申請の更新バリデーション
  def overtime_params_updated_invalid?
    if @attendance.updated_finished_at.present? || @attendance.finished_at.present?
      if ((params[:attendance]["endtime_at(4i)"].to_i > @worktime.hour) ||
          params[:attendance][:tommorow_index] == "true")
        return true
      else
        return false
      end
    else
     return false
    end
  end
  

  # 残業申請のお知らせモーダルの更新バリデーション
  def overtime_notice_updated_invalid?
    items = []
    notice_overtime_params.each do |id, item|
      # attendance = Attendance.find(id)
      items << item[:overtime_check]
    end
    if  items.all?{|i| i == "false"}
      return false
    else
      return true
    end
  end

  # 勤怠変更申請のお知らせモーダルの更新バリデーション
  def change_attendance_updated_invalid?
    items = []
    change_attendance_params.each do |id, item|
    # attendance = Attendance.find(id)
      items << item[:attendance_change_check]
    end
    if  items.all?{|i| i == "false"}
      return false
    else
      return true
    end
  end

  def users(notice_users)
    notice_users.each do |user|
      @notice_overtimes = Attendance.where(user_id: user.id).where.not(endtime_at: nil).where(overtime_check: false)
      @notice_overtimes.each do |att_notice|
        @att_notice = att_notice
      end
    end
  end
end

app/views/attendances/_edit_change_attendance.erb
<% provide(:button_text, '変更を送信する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <%= form_with(model: @att_update_list, url: update_change_attendance_user_attendance_path(@user, @att_up), local: true, method: :patch) do |f| %>
      <% @users.each do |user| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h3 class="modal-title text-center">【<%= user.name %>】からの勤怠変更申請</h3>
        </div>
        <table class="table table-bordered table-condensed table-hover table-striped" id="table-attendances">
          <thead>
            <tr>
              <th rowspan="3" colspan="3">日付</th>
              <th rowspan="3" colspan="3">曜日</th>
              <th colspan="4">変更前</th>
              <th colspan="4">変更後</th>
              <th rowspan="3" width="200px">備考</th>
              <th rowspan="3">支持者確認㊞</th>
              <th rowspan="3">変更</th>
              <th rowspan="3">勤怠を確認する</th>
            </tr>
            <tr>
              <th colspan="2">出社</th>
              <th colspan="2">退社</th>
              <th colspan="2">出社</th>
              <th colspan="2">退社</th>
              
            </tr>
            <tr>
              <th>時</th>
              <th>分</th>
              <th>時</th>
              <th>分</th>
              <th>時</th>
              <th>分</th>
              <th>時</th>
              <th>分</th>
            </tr>
          </thead>
          <% @per_user_attendances = Attendance.where(user_id: user.id).where(id: @att_update_list).where(attendance_change_check: false) %>
            <% @per_user_attendances.each do |day| %>
            <%= f.fields_for "updated_attendances[]", day do |attendance| %>
              <tbody>
                <tr>
                  <!-- 日付 -->
                  <td colspan="3"><%= l(day.worked_on, format: :short) %></td>
                  <!-- 曜日 -->
                  <td colspan="3" class = "<%= css_class(day.worked_on) %>">
                    <%= $days_of_the_week[day.worked_on.wday] %>
                  </td>
                  <!-- 変更前(出/退) -->
                    <!-- 出勤 -->
                    <td><%= day.before_started_at.present? ? l(day.before_started_at, format: :hour) : nil %></td>
                    <td><%= day.before_started_at.present? ? l(day.before_started_at, format: :minute) : nil %></td>
                    <!-- 退勤 -->
                    <td><%= day.before_finished_at.present? ? l(day.before_finished_at, format: :hour) : nil %></td>
                    <td><%= day.before_finished_at.present? ? l(day.before_finished_at, format: :minute) : nil %></td>
                  <!-- 変更後(出/退) -->
                    <!-- 出勤 -->
                    <td><%= day.updated_started_at.present? ? l(day.updated_started_at, format: :hour) : nil %></td>
                    <td><%= day.updated_started_at.present? ? l(day.updated_started_at, format: :minute) : nil %></td>
                    <!-- 退勤 -->
                    <td><%= day.updated_finished_at.present? ? l(day.updated_finished_at, format: :hour) : nil %></td>
                    <td><%= day.updated_finished_at.present? ? l(day.updated_finished_at, format: :minute) : nil %></td>
                  <!-- 備考 -->
                  <td><%= attendance.text_field :note, readonly: true, class: "form-control" %></td>
                  <!-- 支持者確認㊞ -->
                  <td><%= attendance.select :confirm, Attendance.confirms.keys.to_a, include_blank: true, selected: nil %></td>
                  <!-- 変更 -->
                  <td><%= attendance.check_box :attendance_change_check, {class: "change"}, 'true', 'false' %></td>
                  <!-- 勤怠を確認する -->
                  <td><%= link_to "確認", user_path(user.id), class: "btn btn-primary btn-md" %></td>
              </tr>
              </tbody>
            <% end %>
            <% end %>
        </table>
      <% end %>
      <div class="notice_update_submit"><%= f.submit yield(:button_text), class: "btn btn-primary btn-lg center-block" %></div>
    <% end %>
  </div>
</div>

app/views/attendances/_edit_notice_overtime.html.erb
<% provide(:button_text, '変更を送信する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          <%= form_with(model: @notice_overtimes, url: update_notice_overtime_user_attendance_path(@user, @att_notice), local: true, method: :patch) do |f| %>
          <% @notice_users.each do |user| %>
          <h3 class="modal-title text-center">【<%= user.name %>】からの残業申請</h3>
          <table class="table table-bordered table-condensed table-hover table-striped" id="table-attendances">
            <thead>
              <tr>
                <th>日付</th>
                <th>曜日</th>
                <th>終了予定時間</th>
                <th>指定勤務終了時間</th>
                <th>時間外時間</th>
                <th>業務処理内容</th>
                <th>指示者確認㊞</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
              </tr>
            </thead>
            
            <% @attendance_notices = Attendance.where(name: current_user.name).where(user_id: user.id).where.not(endtime_at: nil).where(overtime_check: false) %>
            <% @attendance_notices.each do |att_notice| %>
              <%= f.fields_for "notice_attendances[]", att_notice do |attendance| %>
              <tbody>
                <tr>
                  <!-- 日付 -->
                  <td><%= l(att_notice.worked_on, format: :short) %></td>
                    <!-- 曜日 -->
                    <td class = "<%= css_class(att_notice.worked_on) %>"><%= $days_of_the_week[att_notice.worked_on.wday] %></td>
                    <!-- 終了予定時間 -->
                    <td>
                      <% if att_notice.tommorow_index == true %>
                        <%= att_notice.endtime_at.tomorrow.strftime("%H.%M") if att_notice.endtime_at.present? %>
                      <% else %>
                        <%= att_notice.endtime_at.strftime("%H.%M") if att_notice.endtime_at.present? %>
                      <% end %>
                    </td>
                    <!-- 指定勤務終了時間 -->
                    <td><%= format_basic_info(user.designated_work_end_time) %></td>
                    <!-- 時間外時間 -->
                    <td><%= over_time(att_notice.endtime_at.strftime("%H:%M:%S"), user.designated_work_end_time.strftime("%H:%M:%S"), att_notice)  if att_notice.endtime_at.present? %></td>
                    <!-- 業務処理内容 -->
                    <td><%= attendance.text_field :overtime_memo, readonly: true %></td>
                    <!-- 指示者確認㊞ -->
                    <td><%= attendance.select :overtime_confirm, Attendance.confirms.keys.to_a, include_blank: true, selected: nil %></td>
                    <!-- 変更 -->
                    <td><%= attendance.check_box :overtime_check, {class: "change"}, 'true', 'false' %></td>
                    <!-- 勤怠を確認する -->
                    <td><%= link_to "確認", user_path(user.id), class: "btn btn-primary btn-md" %></td>
                </tr>
              </tbody>
              <% end %>
            <% end %>
          </table>
          <% end %>
          <div class="notice_update_submit"><%= f.submit yield(:button_text), class: "btn btn-primary btn-lg center-block" %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_overtime_app.html.erb
<% provide(:button_text, '変更を送信する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">【残業申請】</h1>
    </div>
    <% @attendances.each do |day| %>
      <%= form_with(model: @attendances, url: update_over_app_user_attendance_path(@user, day), local: true, method: :patch) do |f| %>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12">
            <table class="table table-bordered table-condensed table-hover table-striped" id="table-attendances">
              <thead>
                <tr>
                  <th>日付</th>
                  <th>曜日</th>
                  <th>終了予定時間</th>
                  <th>翌日</th>
                  <th>業務処理内容</th>
                  <th>支持者確認㊞</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <!-- 日付 -->
                  <td><%= l(day.worked_on, format: :short) %></td>
                  <!-- 曜日 -->
                  <td class= "<%= css_class(day.worked_on) %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
                  <!-- 終了予定時間 -->
                  <td><%= f.time_select :endtime_at, {}, class: 'form-control bootstrap-date' %></td>
                  <!-- 翌日 -->
                  <td><%= f.check_box :tommorow_index, {class: "tommorow_index"}, 'true', 'false' %></td>
                  <!-- 業務処理内容 -->
                  <td><%= f.text_field :overtime_memo, :size => "20", class: "form-control" %></td>
                  <!-- 支持者確認㊞ -->
                  <% unless current_user.superior? %>
                    <td><%= f.collection_select :name,  @superiors, :name, :name, :prompt =>"上長を選択してください。" %></td>
                  <% else %>
                    <td><%= f.collection_select :name, User.where.not(name: @user.name).where(superior: true), :name, :name, :prompt =>"上長を選択してください。" %></td>
                  <% end %>
                </tr>
              </tbody>
            </table>
            <div><%= f.submit yield(:button_text), class: "btn btn-primary btn-block" %></div>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/_form_employee_notice.html.erb
<h3 class="modal-notice-title">【<%= @user.name %>からの残業申請】</h3>
   <table class="table table-bordered table-condensed table-hover table-striped" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>終了予定時間</th>
        <th>指定勤務終了時間</th>
        <th>時間外時間</th>
        <th>業務処理内容</th>
        <th>指示者確認㊞</th>
        <th>変更</th>
        <th>勤怠を確認する</th>
      </tr>
    </thead>
    <tbody>
      <% @users_notice.each do |user| %>
        <tr>
          <td><%= l(user.worked_on, format: :short) %></td>
          <td class= "<%= css_class(user.worked_on) %>"><%= $days_of_the_week[user.worked_on.wday] %></td>
          <td><%= l(user.endtime_at, format: :time) %></td>
          <td><%= format_basic_info(@user.designated_work_end_time) %></td>
          <td>
            <% if user.endtime_at.present? && user.finished_at.present? %>
              <%= format("%.2f", Time.at(work_end_time(user)).utc.strftime('%H')) %>
            <% end %>
          </td>
          <td><%= user.overtime_memo %></td>
          <td><%= user.name %></td>
          <td><%= f.check_box :change, {class: "change"}, 'true', 'false' %></td>
          <td><%= f.submit "確認", class: "btn btn-primary btn-md" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="center">
    <%= f.submit yield(:button_text), class: "btn btn-primary btn-block" %>
  </div>

app/views/attendances/edit_change_attendance.js.erb
$("#edit_change_attendance").html("<%= escape_javascript(render 'edit_change_attendance') %>");
$("#edit_change_attendance").modal("show");

app/views/attendances/edit_notice_overtime.js.erb
$("#edit_notice_overtime").html("<%= escape_javascript(render 'edit_notice_overtime') %>");
$("#edit_notice_overtime").modal("show");

app/views/attendances/edit_one_month.html.erb
<% provide(:tittle, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="table table-bordered table-condensed table-hover table-striped" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出社</th>
          <th>退社</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th>備考</th>
          <th>指示者確認㊞</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
            <tr>
              <!-- 日付 -->
              <td><%= l(day.worked_on, format: :short) %></td>
              <!-- 曜日 -->
              <td class= "<%= css_class(day.worked_on) %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
              <% if(!current_user.admin? || current_user.admin?) && (Date.current < day.worked_on) %>
                <!-- 出社 -->
                <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
                <!-- 退社 -->
                <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
              <% else %>
                <!-- 勤怠編集された出退勤時間を判別 -->
                <!-- 出社 -->
                <td><%= attendance.time_field :updated_started_at, class: "form-control" %></td>
                <!-- 退社 -->
                <td><%= attendance.time_field :updated_finished_at, class: "form-control" %></td>
              <% end %>
              <!-- 翌日 -->
              <td><%= attendance.check_box :tommorow_index, {class: "tommorow_index"}, 'true', 'false' %></td>
              <!-- 在社時間 -->
              <td>
                <% if day.updated_started_at.present? && day.updated_finished_at.present? %>
                  <%= working_time(day.updated_started_at, day.updated_finished_at, day) %>
                <% end %>
              </td>
              <% if(!current_user.admin? || current_user.admin?) && (Date.current < day.worked_on) %>
                <!-- 備考 -->
                <td><%= attendance.text_field :note, readonly: true, class: "form-control" %></td>
                <!-- 指示者確認㊞ -->
                <td><%= attendance.collection_select :name, {}, {}, {}, {}, disabled: true, class: "select" %></td>
              <% else %>
                <!-- 備考 -->
                <td><%= attendance.text_field :note, class: "form-control" %></td>
                <!-- 指示者確認㊞ -->
                <td><%= attendance.collection_select :name, User.where(superior: true).where.not(name: @user.name), :name, :name, include_blank: true, selected: nil, class: "select" %></td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="center">
    <%= f.submit "まとめて更新", class: "btn btn-lg btn-primary" %>
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %>
  </div>
<% end %>