config/routes.rb
Rails.application.routes.draw do

  resources :bases

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :attendances do
    collection do
      get 'csv_output'
    end
  end
    
  resources :users do
    collection { post :import }
    get 'import', to: 'users#import'
    get 'index_attendance', to: 'users#index_attendance'
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/edit_attendance_log'
      get 'attendances/edit_notice_overtime'
      get 'attendances/edit_change_attendance'
      post 'approvals/create'
      get 'approvals/edit'
    end
    resources :attendances do
      patch 'update'
      # datetimeのnew
      get 'new'
      member do      
        # 残業申請モーダル
        get 'edit_overtime_app'
        patch 'update_over_app'
        # 残業申請のお知らせモーダルの更新
        patch 'update_notice_overtime'
        # 勤怠変更申請のお知らせモーダルの更新
        patch 'update_change_attendance'
      end
    end
    resources :approvals do
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if current_user && current_user.admin? %>
      <%= link_to "勤怠システム", "#", id: "logo" %>
    <% else %>
      <%= link_to "勤怠システム", current_user, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if !logged_in? %>
          <li><%= link_to "トップへ", root_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>

        <% if logged_in? %>
          <li><%= link_to "トップへ", current_user %></li>
            <% if logged_in? && current_user.admin? %>
              <li><%= link_to "ユーザ一覧", users_path %></li>
              <li><%= link_to "出勤社員一覧", user_index_attendance_path(current_user) %></li>
              <li><%= link_to "拠点情報の修正", bases_path %></li>
              <li><%= link_to "基本情報の修正", edit_basic_info_user_path(current_user) %></li>
            <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "勤怠", current_user %></li>
              <li><%= link_to "個人情報編集", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <!-- HTML shimがこの1行で収まる -->
    <%= render 'layouts/shim' %>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
    <% flash.each do |message_type, msg| %>
      <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
    <% end %>
    
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>